algoritmo "Numero_par_impar_pos_neg"
// Função :
// Autor : Fábio Aragão
// Data : 24/03/2016
// Seção de Declarações 
var
num : inteiro
inicio
escreva("Digite um numero: ")
leia(num)
   se (num % 2 = 0) entao
      escreval("Este numero é PAR!!!")
      senao
      escreval("Este numero é IMPAR!!!")
   fimse
      se(num >=0 ) entao
      escreval("Este numero é POSITIVO!!!")
      senao
      escreval("Este numero é NEGATIVO!!!")
   fimse
   fimalgoritmo
